###POST request to create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Franz Kafka",
  "email": "franz.kafka@example.com",
  "address": "11 House Road",
  "dateOfBirth": "2000-05-11",
  "registeredDate": "2025-04-11"
}